language: objective-c

osx_image: xcode9

xcode_project: NewProject.xcodeproj

xcode_scheme: NewProjectTests

Script:

 - xctool -project NewProject.xcodeproj -scheme NewProject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO