language: objective-c

xcode_project: ./NewProject.xcodeproj

xcode_scheme: NewProjectTests

osx_image: xcode9

#Script:

 #- xctool -project NewProject.xcodeproj -scheme NewProject -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
